.PHONY: install
install:
	npm install

.PHONY: dev
dev:
	npm run dev

.PHONY: build
build:
	npm run build

.PHONY: preview
preview:
	npm run preview

.PHONY: lint
lint:
	npm run lint

.PHONY: clean
clean:
	rm -rf node_modules dist
